example:
	g++ -o example -Iinclude example.cpp -L.  lib/libmysqlclient.so.18.3.0 

example2:
	g++ -o example2 -Iinclude example2.cpp -L.  lib/libmysqlclient.so.18.3.0 

example3:
	g++ -o example3 -Iinclude example3.cpp -L.  lib/libmysqlclient.so.18.3.0 

